# Generated by Django 5.2 on 2025-05-09 08:52

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_word_choices',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='game_state',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
