# Generated by Django 5.2 on 2025-05-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_current_word_choices_gameroom_game_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('choice', 'Choix du mot'), ('clue', 'Donner un indice'), ('guess', 'Deviner le mot')], default='choice', max_length=10)),
                ('word', models.CharField(blank=True, max_length=100)),
                ('required_clues', models.IntegerField(null=True)),
                ('given_clues', models.JSONField(default=list)),
                ('given_guesses', models.JSONField(default=list)),
                ('guessing_players', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('word_found', models.BooleanField(default=False)),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gameroom')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='current_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.round'),
        ),
    ]
