# Generated by Django 5.2 on 2025-05-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_round_gameroom_current_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='game_state',
        ),
    ]
