# Generated by Django 5.2 on 2025-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_round_all_guesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='completed_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='total_rounds',
            field=models.IntegerField(default=2),
        ),
    ]
