# Generated by Django 5.2 on 2025-05-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gameroom_completed_rounds_gameroom_total_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player_order',
            field=models.JSONField(default=list),
        ),
    ]
