# Generated by Django 5.2 on 2025-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameroom_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='can_malus',
            field=models.BooleanField(default=False),
        ),
    ]
